version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    build: .
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.development.env
    ports:
      - "7000:7000"
    command: sh -c "bun run migrate && bun run seed-all && bun run dev"

volumes:
  db_data:
